// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNu1gR5YNFZVNg6bl1NVCx3-M8zX35B5I',
    appId: '1:975093254525:web:75f9106160b54a6fd9a414',
    messagingSenderId: '975093254525',
    projectId: 'vdsmanager',
    authDomain: 'vdsmanager.firebaseapp.com',
    databaseURL: 'https://vdsmanager-default-rtdb.firebaseio.com',
    storageBucket: 'vdsmanager.firebasestorage.app',
    measurementId: 'G-XZESH0R9YL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5u5JaJwjA9xWaT323dilwolnP1-FLnC8',
    appId: '1:975093254525:android:2413c81feaf07c15d9a414',
    messagingSenderId: '975093254525',
    projectId: 'vdsmanager',
    databaseURL: 'https://vdsmanager-default-rtdb.firebaseio.com',
    storageBucket: 'vdsmanager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT3VvCROb9waTNV_i4XCohHOZ0NeYeUmY',
    appId: '1:975093254525:ios:ffefd27432d8aa66d9a414',
    messagingSenderId: '975093254525',
    projectId: 'vdsmanager',
    databaseURL: 'https://vdsmanager-default-rtdb.firebaseio.com',
    storageBucket: 'vdsmanager.firebasestorage.app',
    androidClientId: '975093254525-vdj732pdbcts3o5je8saes2b3ad77s28.apps.googleusercontent.com',
    iosClientId: '975093254525-vp0o6ufridvgcqk50pgv95917a557hag.apps.googleusercontent.com',
    iosBundleId: 'com.vishrutdonda.vdShiftManager',
  );

}